name: SateScrolls
version: '${project.version}'
main: org.comp.progiple.satescrolls.SateScrolls
api-version: '1.16'
commands:
  satescrolls:
    aliases:
      - ss
      - scroll
      - scrolls
      - sates
      - sscrolls
      - sscroll
permissions:
  satescrolls.admin:
    default: op